services:
  routstr:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
      - tor-data:/var/lib/tor:ro
    env_file:
      - .env
    environment:
      - TOR_PROXY_URL=socks5://tor:9050
    ports:
      - 8000:8000
    extra_hosts: # Needed to access locally running models
      - "host.docker.internal:host-gateway"

  tor:
    image: ghcr.io/hundehausen/tor-hidden-service:latest
    volumes:
      - tor-data:/var/lib/tor
    environment:
      # Format: HS_<NAME>=<TARGET_HOST>:<TARGET_PORT>:<VIRTUAL_PORT>
      - HS_ROUTER=routstr:8000:80
    depends_on:
      - routstr

volumes:
  tor-data:
