"""add model paths table

Revision ID: 4e0c3d195a49
Revises: 7f2843d3f4e4
Create Date: 2026-07-24 21:14:39.062179
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e0c3d195a49"
down_revision = "7f2843d3f4e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_paths",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("upstream_provider_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["upstream_provider_id"], ["upstream_providers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "model_id",
            "path",
            "upstream_provider_id",
            name="uq_model_paths_model_path_provider",
        ),
    )
    op.create_index(
        op.f("ix_model_paths_model_id"), "model_paths", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_paths_upstream_provider_id"),
        "model_paths",
        ["upstream_provider_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_paths_upstream_provider_id"), table_name="model_paths")
    op.drop_index(op.f("ix_model_paths_model_id"), table_name="model_paths")
    op.drop_table("model_paths")
    # ### end Alembic commands ###
