"""alias-ids

Revision ID: b9667ffc5701
Revises: lightning_invoices
Create Date: 2025-12-25 19:30:44.673350
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9667ffc5701"
down_revision = "lightning_invoices"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column(
        "models",
        sa.Column("canonical_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "models",
        sa.Column("alias_ids", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "alias_ids")
    op.drop_column("models", "canonical_slug")
    # ### end Alembic commands ###
